prSections:
- title: My Pull Requests
  filters: is:open author:@me
- title: Needs My Review
  filters: is:open review-requested:@me
- title: Subscribed
  filters: is:open -author:@me repo:cli/cli repo:dlvhdr/gh-dash
issuesSections:
- title: My Issues
  filters: is:open author:@me
- title: Assigned
  filters: is:open assignee:@me
- title: Subscribed
  filters: is:open -author:@me repo:cli/cli repo:dlvhdr/gh-dash
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 20
  issuesLimit: 20
  view: prs
keybindings:
  prs: []
repoPaths: {}
