#!/bin/bash
# Install Monaco font in Linux
# Version from nullvideo https://gist.github.com/rogerleite/99819#gistcomment-2799386

# Load utility functions
source "$(dirname "$0")/utils.zsh"

# Monaco font installation

# Create font directory (using execute_command for error handling)
execute_command \
	"sudo mkdir -p /usr/share/fonts/truetype/ttf-monaco" \
	"Font directory created." \
	"Failed to create font directory."

# Download font (using execute_command)
execute_command \
	"sudo wget https://gist.github.com/rogerleite/b50866eb7f7b5950da01ae8927c5bd61/raw/862b6c9437f534d5899e4e68d60f9bf22f356312/mfont.ttf -O /usr/share/fonts/truetype/ttf-monaco/Monaco_Linux.ttf" \
	"Monaco font downloaded." \
	"Failed to download Monaco font."

# Update font cache (using execute_command)
execute_command \
	"sudo fc-cache" \
	"Font cache updated." \
	"Failed to update font cache."

gum_style "Monaco font installation completed." # Or just echo "Monaco font installed."
