#!/bin/zsh

# Load utility functions
source "$(dirname "$0")/utils.zsh"

gum_style "Starting Spotify installation..."

# Ensure curl is installed
ensure_dependency "curl"

# Add Spotify GPG key
execute_command \
    "curl -sS https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg | sudo gpg --dearmor --yes -o /etc/apt/trusted.gpg.d/spotify.gpg" \
    "Spotify GPG key added successfully." \
    "Failed to add Spotify GPG key."

# Add Spotify repository
execute_command \
    "echo 'deb http://repository.spotify.com stable non-free' | sudo tee /etc/apt/sources.list.d/spotify.list > /dev/null" \
    "Spotify repository added successfully." \
    "Failed to add Spotify repository."

# Update package list
execute_command \
    "sudo apt-get update" \
    "Package list updated successfully." \
    "Failed to update package list."

# Install Spotify client
execute_command \
    "sudo apt-get install -y spotify-client" \
    "Spotify client installed successfully." \
    "Failed to install Spotify client."


# Verify installation
verify_installation "spotify"

gum_style "Spotify installation completed successfully!"
