#!/usr/bin/env zsh
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="bat,bin,fzf,git,goneovim,helix,kitty,lsd,nushell,nvim,postman,ripgrep,rofi,s,spacemacs,starship,stylua,taskwarrior,tmux,tmuxinator,vimium,zsh"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/dotfiles
fi

STOW_FOLDERS=$STOW_FOLDERS DOTFILES=$DOTFILES $DOTFILES/install
