-- NOTE: commenting out this because it was enabling colorizer by default for
-- all the buffers and we don't want that
-- require("colorizer").setup({
--     -- filetype = { "*" },
--     user_default_options = {
--         mode = "background", -- Set the display mode.
--     },
-- })
