-- local ok, noice = lk.require("noice")
-- if not ok then
--     return
-- end

-- noice.setup({
--     routes = {
--         {
--             filter = {
--                 event = "msg_show",
--                 kind = "",
--                 find = "written",
--             },
--             opts = { skip = true },
--         },
--         {
--             filter = {
--                 event = "msg_show",
--                 kind = "search_count",
--             },
--             opts = { skip = true },
--         },
--     },
--     presets = {
--         bottom_search = false, -- use a classic bottom cmdline for search
--         command_palette = true, -- position the cmdline and popupmenu together
--         long_message_to_split = true, -- long messages will be sent to a split
--         inc_rename = false, -- enables an input dialog for inc-rename.nvim
--     },
-- })
