-- NOTE: general
-- require('lk.plugins.neuron')
require('lk.plugins.abolish')
require('lk.plugins.auto-pairs')
require('lk.plugins.bufferline')
require('lk.plugins.closetag')
require('lk.plugins.colorizer')
require('lk.plugins.completion')
require('lk.plugins.crease')
require('lk.plugins.dap')
require('lk.plugins.devicons')
require('lk.plugins.emmet')
require('lk.plugins.fastfold')
require('lk.plugins.fist')
require('lk.plugins.floaterm')
require('lk.plugins.fnr')
require('lk.plugins.formatter')
require('lk.plugins.fugitive')
require('lk.plugins.gitblame')
require('lk.plugins.gitmessenger')
require('lk.plugins.gitsigns')
require('lk.plugins.goyo')
require('lk.plugins.harpoon')
require('lk.plugins.hlslens')
require('lk.plugins.hlslens')
require('lk.plugins.hop')
require('lk.plugins.indentlines')
require('lk.plugins.lspsaga')
require('lk.plugins.markdown')
require('lk.plugins.neogit')
require('lk.plugins.nvim-bqf')
require('lk.plugins.nvim-tree')
require('lk.plugins.openbrowser')
require('lk.plugins.quickscope')
require('lk.plugins.sideways')
require('lk.plugins.snippets')
require('lk.plugins.startify')
require('lk.plugins.tagalong')
require('lk.plugins.toggleterm')
require('lk.plugins.treesitter')

-- NOTE: fuzzy
require('lk.plugins.telescope')
require('lk.plugins.telescope.mappings')

-- NOTE: LSPs
-- require('lk.plugins.coc')
require('lk.plugins.nvim_lsp')
