-- NOTE: general
-- require('lk.plugins.fuzzy')
-- require('lk.plugins.kommentary')
-- require('lk.plugins.lightbulb')
-- require('lk.plugins.lspkind')
-- require('lk.plugins.lspsaga')
-- require('lk.plugins.neofs')
-- require('lk.plugins.neuron')
-- require('lk.plugins.snippets')
-- require('lk.plugins.terminal')
require('lk.plugins.auto-pairs')
require('lk.plugins.bufferline')
require('lk.plugins.colorizer')
require('lk.plugins.devicons')
require('lk.plugins.formatter')
require('lk.plugins.fugitive')
require('lk.plugins.gitsigns')
require('lk.plugins.goyo')
require('lk.plugins.harpoon')
require('lk.plugins.hlslens')
require('lk.plugins.hop')
require('lk.plugins.indentlines')
require('lk.plugins.neogit')
require('lk.plugins.nvim-bqf')
require('lk.plugins.nvim-tree')
require('lk.plugins.treesitter')

-- NOTE: fuzzy
require('lk.plugins.telescope')
require('lk.plugins.telescope.mappings')
