return {
    -- "build.on_save",
    "build.cpp.build_and_run",
    "build.cpp.index",
    "build.go",
    "build.node",
    "build.python",
    "npm.build",
    "npm.dev",
    "npm.install",
    "npm.start",
    "npm.budgets",
    "npm.tsc_watch",
    "rust.rustlings",
    "yarn.build",
    "yarn.dev",
    "yarn.install",
    "yarn.budgets",
    "yarn.tsc_watch",
}
