vim.api.nvim_create_user_command("Google", function(o)
    -- local escaped = require('socket.url').escape(o.args)
    local escaped = vim.uri_encode(o.args)
    local url = ("https://www.google.com/search?q=%s"):format(escaped)
    vim.ui.open(url)
end, { nargs = 1, desc = "just google it" })

vim.api.nvim_create_user_command("DuckDuckGo", function(o)
    -- local escaped = require('socket.url').escape(o.args)
    local escaped = vim.uri_encode(o.args)
    local url = ("https://duckduckgo.com/?q=%s"):format(escaped)
    vim.ui.open(url)
end, { nargs = 1, desc = "just google i mean duckduckgo it" })

vim.api.nvim_create_user_command("Reddit", function(o)
    -- local escaped = require('socket.url').escape(o.args)
    local escaped = vim.uri_encode(o.args)
    local url = ("https://reddit.com/r/neovim/search?q=%s&restrict_sr=on"):format(escaped)
    vim.ui.open(url)
end, { nargs = 1, desc = "search in r/neovim" })
