# ~/.goneovim/setting.toml

[Editor]
## If it is set to true, applications will be launched in a borderless window, except for Linux.
## The default value is false.
BorderlessWindow = true
## Editor minimum window width (>= 400)
Width = 800
## Editor minimum window height (>= 300)
Height = 600

## Editor external font-family, font-size, and linespace.
## This is the font and linespace settings of the graphical UI as an nvim front end.
## For example, linespace affects the margins of the external completion popup menu UI.
## Font settings in nvim are set with well-known options, such as `:set guifont = hoge:h10`, `:set linespace=4`.
# FontFamily = "OperatorMono Nerd Font"
# FontFamily = "OperatorMono Lig Book"
FontFamily = "CaskaydiaCove Nerd Font"
FontSize = 10
Linespace = 6

## Neovim external UI features
## The following is the default value of goneovim.
## You can change the behavior of the GUI by changing the following boolean values.
## If you prefer the traditional Vim UI, set it to false for all.
## Also, `ExtMessages` is still experimental at this time and we don't recommend setting it to true if you want stability.
ExtCmdline   = true
ExtPopupmenu = false
ExtTabline   = true
ExtMessages  = false

## Copy yanked text to clipboard
Clipboard = true

## This is the equivalent of the macmeta configuration in MacVim
Macmeta = true

## Goneovim has a cached rendering feature enabled to speed up the process.
## If you want to disable it, set it to false
CachedDrawing = true
## You can specify the cache size to be used by the cache rendering feature of goneovim.
## The default is 320.
CacheSize = 320

## The input method editor will be automatically disabled when the mode is changed to normal mode.
## It may be useful for users who use the input method editor (e.g. East Asian People).
DisableImeInNormal = false

## You can write a vimscript to be executed after goneovim starts,
## for example to disable the vimscript that Goneovim has embedded internally.
# GinitVim = '''
#  let g:hoge =fuga
# '''

## Launch goneovim with full screen window size.
StartFullscreen = true

## This option makes the whole GUI window in semi-transparent.
## This setting also implicitly enables the Drawborder setting
Transparent = 0.9

## Draw window separator on the GUI side instead of the vertical border and status line that nvim draws.
DrawWindowSeparator = false
WindowSeparatorTheme = "dark"
# WindowSeparatorColor = "#adb3b8"
WindowSeparatorGradient = true


## Draw built-in indent guide
IndentGuide = true
# IndentGuideIgnoreFtList = ["md"]

## Draw border on a float window
# DrawBorderForFloatWindow = false

## Draw shadow under a float window
# DrawShadowForFloatWindow = false

## Enable desktop notification settings for nvim messages.
## This option works only if `ExtMessages` is enabled.
DesktopNotifications = false


# Pattern that fills the diff background
# Change the background pattern used for diff display.
# This option allows you to use a visual effect pattern such as Dense, Diagonal Stripe instead of a regular solid pattern.
# The available patterns are all Qt brush styles. For more information, See: https://doc.qt.io/qt-5/qbrush.html#details
# // -- diffpattern enum --
# // SolidPattern             1
# // Dense1Pattern            2
# // Dense2Pattern            3
# // Dense3Pattern            4
# // Dense4Pattern            5
# // Dense5Pattern            6
# // Dense6Pattern            7
# // Dense7Pattern            8
# // HorPattern               9
# // VerPattern               10
# // CrossPattern             11
# // BDiagPattern             12
# // FDiagPattern             13
# // DiagCrossPattern         14
# // LinearGradientPattern    15
# // RadialGradientPattern    16
# // ConicalGradientPattern   17
# // TexturePattern           24
DiffAddPattern    = 1
DiffDeletePattern = 1
DiffChangePattern = 1

# Display the effect when clicked
ClickEffect = true

[Palette]
## Specifies the proportion of the command line palette to the height of the entire window.
AreaRatio = 0.5
## Specifies the number of items to be displayed in the command line palette.
MaxNumberOfResultItems = 30
## Specifies the opacity of the command line palette.
Transparent = 1.0

[Message]
## Specifies the opacity of the message window.
Transparent = 1.0

## The statusline configuration below relates to the display of Goneovim's own external status lines.
## If you want to use neovim's status line plugin, you should disable its display.
[Statusline]
## Whether or not to display the external status line
Visible = false

## Options: "textLabel" / "icon" / "background" / "none"
ModeIndicatorType = "textLabel"

## Optional setting colors per Neovim editing modes
NormalModeColor = "#2AFFDF"
CommandModeColor = "#FF9D00"
InsertModeColor = "#ffc600"
ReplaceModeColor = "#229aFF"
VisualModeColor = "#9966cc"
TerminalModeColor = "#219aFF"

# colors from cobalt2 theme
# Yellow: #ffc600
# Orange: #FF9D00
# Mint: #2AFFDF
# Blue: #193549
# Off Blue: #0D3A58 (use on variable bgs)
# Dusty Blue: #35434d
# Dark Blue: #15232D
# Pink: #0B94FF
# Light Blue: #181aFF

## Statusline components
Left = [ "mode", "filepath", "filename" ]
Right = [ "message", "git", "filetype", "fileformat", "fileencoding", "curpos", "lint" ]


[Tabline]
## Whether or not to display the external tabline
Visible = true
ShowIcon = true

[Popupmenu]
## neovim's popupmenu is made up of word, menu and info parts.
## Each of these parts will display the following information.
##   word:   the text that will be inserted, mandatory
##   menu:   extra text for the popup menu, displayed after "word"
##   info:   more information about the item, can be displayed in a preview window

## The following options specify whether to display a dedicated column in the popupmenu
## to display the long text displayed in the `info` part.
ShowDetail = true

## total number to display item
Total = 20

## width of `menu` column
MenuWidth = 400

## width of `info` column
InfoWidth = 1

## width of `detail` column
DetailWidth = 250

[Lint]
## Specifies whether the external linter tooltip should be displayed or not.
Visible = true

[MiniMap]
## To view the minimap, launch an additional nvim instance;
## setting Disable to true will not launch this additional nvim instance
## and will completely disable the minimap feature.
Disable = false

## Specifies whether to show the minimap or not.
Visible = false

## Specifies the width of the minimap.
Width = 120

[ScrollBar]
## Specifies whether to show the external scrollbar or not.
Visible = false

[SideBar]
## Specifies whether to show the external sidebar or not.
Visible = false

## Specify whether or not to draw a shadow under the sidebar.
DropShadow = true

## Specify the sidebar width
Width = 200

## Specify the color to use when selecting items in the sidebar or palette in hexadecimal format
AccentColor = "#A9A9A9"

[Workspace]
## This setting sets the format of the path string of CWD in the sidebar.
##  name: directoryname
##  full: /path/to/directoryname
##  minimum: /p/t/directoryname
PathStyle = "name"

## Specifies whether the last exited session should be restored at the next startup.
RestoreSession = true

[FileExplore]
## Specify the maximum number of items to be displayed in the file explorer.
MaxDisplayItems = 30
