#-------------------------------------------------------------------------------
# # NOTE: scratchpads settings {{{
#-------------------------------------------------------------------------------

for_window [class="Spotify"] resize set 1800 1000
for_window [class="Todoist"] resize set 1800 1000
# for_window [class="Blueman-manager"] resize set 1080 1000
# for_window [class="Thunar"] resize set 1800 1000
for_window [class="xpad"] resize set 500 400
for_window [title="monitor"] resize set 1880 1000
for_window [class="gnome-pomodoro"] resize set 1800 1000
for_window [title="alsamixer"] resize set 1800 1000
for_window [class="copyq"] resize set 600 1000
for_window [class="Espanso"] resize set 800 500
for_window [class="gnome-calendar"] resize set 1800 1000


for_window [title="floating-notes"] resize set 1800 1000
for_window [title="floating-scratch"] resize set 1800 1000
for_window [title="floating-todos"] resize set 1800 1000
for_window [class="neovide-notes"] resize set 1200 800
for_window [class="neovide-todos"] resize set 1200 800
for_window [class="neovide-scratch"] resize set 1500 800
for_window [class="floating-nvim"] resize set 1800 1000
for_window [title="scratch-terminal"] resize set 1800 1000
for_window [title="terminal-music-player"] resize set 1800 1000
for_window [title="wallpaper-selector"] resize set 1800 1000
for_window [title="second-brain-search"] resize set 1800 1000

# >> pake applications (deprecated)
# for_window [class="(?i)pake-gemini"] resize set 1800 1000
# for_window [class="(?i)pake-whatsapp"] resize set 1800 1000
# for_window [class="(?i)pake-programmusic"] resize set 1800 1000
# for_window [class="(?i)pake-notebooklm"] resize set 1800 1000

# >> brave pwa scratchpads
# YouTube Music
for_window [instance="crx_cinhimbnkkaeohfgghhklpknlkffjgod"] resize set 1800 1000
# Google Gemini
for_window [instance="crx_gdfaincndogidkdcdkhapmbffkckdkhn"] resize set 1800 1000
# WhatsApp Web
for_window [instance="crx_hnpfjngllnobngcgfapefoaidbinmjnm"] resize set 1800 1000
# musicForProgramming
for_window [instance="crx_jhcembbiknekhcfklaahjjojbciaphaa"] resize set 1800 1000
# NotebookLM
for_window [instance="crx_gjcmcplpgihbecacndmmbaenpfgimlec"] resize set 1800 1000
# ChatGPT
for_window [class="Chatgpt"] resize set 1800 1000
# Claude
for_window [instance="crx_fmpnliohjhemenmnlpbfagaolkdacoja"] resize set 1800 1000
# X (Twitter)
for_window [instance="crx_lodlkdfmihgonocnmddehnfgiljnadcf"] resize set 1800 1000
 # Discord
 for_window [instance="crx_pliiebkcmokkgndfalahlmimanmbjlab"] resize set 1800 1000
# Google Keep
for_window [instance="crx_eilembjdkfgodjkcjnpgpaenohkicgjd"] resize set 1800 1000

#-------------------------------------------------------------------------------
#}}}
#-------------------------------------------------------------------------------

# vim:fdm=marker
