#!/usr/bin/env zsh

set -euo pipefail

SCRIPT_DIR="${0:A:h}"
WORKSPACE_DIR="${SCRIPT_DIR:h:h}"
DETECTOR="$WORKSPACE_DIR/tmux/.config/tmux/scripts/git/lib/deps-detect.sh"

if [[ ! -f "$DETECTOR" ]]; then
    print -u2 "FAIL: dependency detector is missing"
    exit 1
fi

source "$DETECTOR"

TEST_DIR=$(mktemp -d)
trap 'rm -rf "$TEST_DIR"' EXIT

expect_command() {
    local name="$1"
    local expected="$2"
    shift 2

    local project="$TEST_DIR/$name"
    mkdir -p "$project"
    for marker in "$@"; do
        mkdir -p "$project/${marker:h}"
        : > "$project/$marker"
    done

    local actual
    actual=$(get_install_command "$project")
    if [[ "$actual" != "$expected" ]]; then
        print -u2 "FAIL: $name: expected '$expected', got '$actual'"
        return 1
    fi
}

expect_yarn_command() {
    local name="$1"
    local expected="$2"
    local lock_contents="$3"
    local project="$TEST_DIR/$name"
    mkdir -p "$project"
    : > "$project/package.json"
    print -r -- "$lock_contents" > "$project/yarn.lock"

    local actual
    actual=$(get_install_command "$project")
    if [[ "$actual" != "$expected" ]]; then
        print -u2 "FAIL: $name: expected '$expected', got '$actual'"
        return 1
    fi
}

expect_command node-pnpm 'pnpm install --frozen-lockfile' package.json pnpm-lock.yaml yarn.lock package-lock.json
expect_yarn_command node-yarn-classic 'yarn install --frozen-lockfile' $'# This file is autogenerated.\n# yarn lockfile v1'
expect_yarn_command node-yarn-modern 'yarn install --immutable' '__metadata:'
expect_command node-bun 'bun install --frozen-lockfile' package.json bun.lock
expect_command node-npm 'npm ci' package.json package-lock.json
expect_command node-default 'npm install' package.json
expect_command python-uv 'uv sync --locked' pyproject.toml uv.lock requirements.txt
expect_command python-poetry 'poetry install' pyproject.toml poetry.lock
expect_command python-pipenv 'pipenv sync' Pipfile Pipfile.lock
expect_command python-requirements 'python3 -m venv .venv && .venv/bin/python -m pip install -r requirements.txt' requirements.txt
expect_command rust 'cargo fetch --locked' Cargo.toml Cargo.lock
expect_command go 'go mod download' go.mod go.sum
expect_command cpp-vcpkg 'vcpkg install' vcpkg.json conanfile.txt
expect_command cpp-conan 'conan install . --build=missing' conanfile.py
expect_command java-maven-wrapper './mvnw -B dependency:go-offline' pom.xml mvnw
expect_command java-maven 'mvn -B dependency:go-offline' pom.xml
expect_command java-gradle-wrapper './gradlew dependencies' build.gradle.kts gradlew
expect_command java-gradle 'gradle dependencies' build.gradle

mkdir -p "$TEST_DIR/home"
export HOME="$TEST_DIR/home"
SCRIPT_DIR="$WORKSPACE_DIR/tmux/.config/tmux/scripts/git"
source "$SCRIPT_DIR/lib/common.sh"
setup_environment
source "$SCRIPT_DIR/lib/deps.sh"

typeset -ga TMUX_NEW_WINDOW_ARGS
tmux() {
    if [[ "$1" == new-window ]]; then
        TMUX_NEW_WINDOW_ARGS=("$@")
    fi
}

plain_project="$TEST_DIR/plain-project"
mkdir -p "$plain_project"
TMUX_NEW_WINDOW_ARGS=()
launch_dependency_install "$plain_project" plain
if (( ${#TMUX_NEW_WINDOW_ARGS} > 0 )); then
    print -u2 "FAIL: launched setup for an unrecognized project"
    exit 1
fi

node_project="$TEST_DIR/node-project"
mkdir -p "$node_project"
: > "$node_project/package.json"
: > "$node_project/package-lock.json"
TMUX_NEW_WINDOW_ARGS=()
launch_dependency_install "$node_project" feature
if [[ "${TMUX_NEW_WINDOW_ARGS[-1]}" != *worktree-deps-install.sh* || "${TMUX_NEW_WINDOW_ARGS[-1]}" != *npm* ]]; then
    print -u2 "FAIL: did not launch the detected dependency command"
    exit 1
fi

hook_project="$TEST_DIR/hook-project"
mkdir -p "$hook_project/node_modules"
: > "$hook_project/package.json"
: > "$hook_project/.worktree-setup"
chmod +x "$hook_project/.worktree-setup"
TMUX_NEW_WINDOW_ARGS=()
launch_dependency_install "$hook_project" hook-only
if [[ "${TMUX_NEW_WINDOW_ARGS[-1]}" != *worktree-deps-install.sh* || "${TMUX_NEW_WINDOW_ARGS[-1]}" == *npm* ]]; then
    print -u2 "FAIL: existing node_modules did not allow the setup hook to run alone"
    exit 1
fi

python_project="$TEST_DIR/python-project"
mkdir -p "$python_project/.venv"
: > "$python_project/requirements.txt"
TMUX_NEW_WINDOW_ARGS=()
launch_dependency_install "$python_project" python
if (( ${#TMUX_NEW_WINDOW_ARGS} > 0 )); then
    print -u2 "FAIL: launched Python setup despite an existing .venv"
    exit 1
fi

print "PASS: worktree dependency detection"
