#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    automatic_update = true
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "codedark"
    colorscheme_bg = "dark"
    guifont = "Cascadia Code 11"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    buffer_index_type = 4
    filemanager = "nerdtree"
    autocomplete_method = "coc"
    disabled_plugins = ["tagbar"]
    search_tools = ["rg"]
    enable_googlesuggest = 1

[[layers]]
  name = "core#statusline"
  enable = false

[[layers]]
name = 'colorscheme'
# random_theme = true
# frequency = "hourly"

[[layers]]
name = 'default'

[[layers]]
name = 'edit'

[[layers]]
name = 'incsearch'

[[layers]]
name = 'fzf'

[[layers]]
name = 'git'
git-plugin = "fugitive"

[[layers]]
name = 'github'

[[layers]]
name = 'format'
format_on_save = true

[[layers]]
name = 'gtags'
gtagslabel = 'ctags'

# [[layers]]
# name = 'tmux'
# tmuxline_separators = 'arrow'
# tmuxline_separators_alt = 'arrow'

[[layers]]
name = 'tools#dash'

[[layers]]
name = "tools#mpv"
mpv_interpreter="/usr/bin/mpv"
musics_directory = '/home/lalit/Music'


[[layers]]
name = 'sudo'

# languages layers
[[layers]]
name = 'lang#extra'

[[layers]]
name = 'lsp'
filetypes = [
  'javascript'
]

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[custom_plugins]]
repo = 'neoclide/coc.nvim'
merged = false

[[custom_plugins]]
repo = 'yuki-ycino/fzf-preview.vim'
#
# [[custom_plugins]]
# repo = 'junegunn/fzf.vim'
# merged = false

[[custom_plugins]]
repo = 'sainnhe/gruvbox-material'
merged = false

[[custom_plugins]]
repo = 'tomasiser/vim-code-dark'
merged = false

[[custom_plugins]]
repo = 'pangloss/vim-javascript'
merged = false

[[custom_plugins]]
repo = 'mxw/vim-jsx'
merged = false
