#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2020 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    autocomplete_method = "coc"
    automatic_update = true
    bootstrap_after = "myspacevim#after"
    bootstrap_before = "myspacevim#before"
    buffer_index_type = 4
    colorscheme = "onedark"
    colorscheme_bg = "dark"
    enable_googlesuggest = 1
    enable_guicolors = true
    enable_statusline_mode = false
    enable_tabline_filetype_icon = true
    enable_vimfiler_gitstatus = true
    enable_vimfiler_welcome = false
    guifont = "Cascadia Code 11"
    search_tools = ["rg"]
    snippet_engine = "ultisnips"

[[layers]]
    name = "core#statusline"
    enable = false

[[layers]]
    name = 'colorscheme'
    random_theme = true
    frequency = "hourly"

[[layers]]
    name = 'default'

[[layers]]
    name = 'edit'

[[layers]]
    name = 'incsearch'

[[layers]]
    name = 'fzf'

[[layers]]
    name = 'git'
    git-plugin = "fugitive"

[[layers]]
    name = 'VersionControl'
    git-plugin = "fugitive"

[[layers]]
    name = 'github'

[[layers]]
    name = 'format'
    format_on_save = true

[[layers]]
    name = 'gtags'
    gtagslabel = 'ctags'

# [[layers]]
    # name = 'tmux'
    # tmuxline_separators = 'arrow'
    # tmuxline_separators_alt = 'arrow'

[[layers]]
    name = 'tools#dash'

[[layers]]
    name = 'sudo'

# languages layers
[[layers]]
    name = 'lang#extra'

[[layers]]
    name = 'lsp'
    filetypes = [
      'javascript',
      # 'javascriptreact',
      # 'typescrpt',
      # 'typescrptreact',
      # 'json',
      # 'lua',
      # 'vim',
      # 'go',
  ]

# Enable autocomplete layer
[[layers]]
    name = 'autocomplete'
    auto_completion_return_key_behavior = "complete"
    auto_completion_tab_key_behavior = "smart"

[[layers]]
    name = 'shell'
    default_position = 'float'
    default_height = 30


[[custom_plugins]]
    repo = 'sainnhe/gruvbox-material'
    merged = false

[[custom_plugins]]
    repo = 'tomasiser/vim-code-dark'
    merged = false

[[custom_plugins]]
    repo = 'itchyny/lightline.vim'
    merged = false
#
[[custom_plugins]]
    repo = 'ryanoasis/vim-devicons'
    merged = false

[[custom_plugins]]
    repo = "lilydjwg/colorizer"
    on_cmd = ["ColorHighlight", "ColorToggle"]
    merged = false
